from secret_data import SECRET_KEY, DATA_DB

DEBUG = True
SECRET_KEY = SECRET_KEY
SQLALCHEMY_DATABASE_URI = DATA_DB
SQLALCHEMY_TRACK_MODIFICATIONS = False
BASE_URL = 'http://127.0.0.1:5000'
SHORT_BASE_URL = 'http://127.0.0.1:5000'
