version: '3'
services:
  web:
    build:
      context: .
      dockerfile:
        docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: example
